# _config.yml overrides for use in local development only, not when building on
# Github for production

# Use the locally installed theme, for faster startup
remote_theme: false
theme: minimal-mistakes-jekyll

# Do not nest paths
baseurl: ""
