collections:
  databases:
    output: true
    permalink: /dataset/:name

# See https://github.com/mmistakes/minimal-mistakes/issues/1875
# for configuring minimal-mistakes theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

title: MathDB
description: A database of mathematical databases
exclude:
  - "DATA.md"
  - "split_data.py"

# Nest link paths under /MathDB
baseurl: /MathDB

defaults: # setting default variables for pages, e.g., layout
  - scope:
      path: "_databases"
    values:
      layout: "dataset"
      # TODO: replace with "database"

github:
  - is_project_page: false
show_downloads:
  false

  # google_analytics: UA-145714554-1
  # hostname: "beantheory.org"
