
collections:
  databases:


theme: jekyll-theme-slate
title: MathDB
description: A database of mathematical databases
exclude:
  - "DATA.md"
  - "split_data.py"
  # google_analytics: UA-145714554-1
  # hostname: "beantheory.org"
